### ISSUE TITLE
Friend Link Exchange Request

### ISSUE THREAD

**Issue by chillcicada** [Andonade/Andonade.github.io#1]
Friend Link Exchange Request | 友链申请 :)

site: https://chillcicada.com
avatar: https://img.chillcicada.com/i/2024/05/31/6659bc90ae368.jpg
description: cc's ruin

---

sukidesu

**Comment by Andonade** [comment]
My Pleasure~

site: https://andonade.github.io
avatar: https://s2.loli.net/2024/04/26/7LRHdZcFeG3WVi9.jpg
description: Normal one. Normal days.

daidaidaisuki

**Comment by chillcicada** [comment]
thanks, i'll update my blog in the next merge, :) ❤️
