### ISSUE TITLE
Have you ckeck that you set discussion enabled?

### ISSUE THREAD

**Issue by chillcicada** [Andonade/Andonade.github.io#2]
refer to https://giscus.app/zh-CN

or reset the repo_id at https://github.com/Andonade/Andonade.github.io/blob/main/_config.redefine.yml#L354 if that doesnt work well

😸

**Comment by Andonade** [comment]
I forgot to update my giscus configuration and enable discussion for this repo, now fixed.

Thank you so much for reminding me of this! :heart_eyes_cat:
